Golf Roster Creator/Controllers/GolferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Golf_Roster_Creator.Models;
using PetaPoco;
using Golf_Roster_Creator.Helpers;

namespace Golf_Roster_Creator.Controllers
{
    public class GolferController : Controller
    {
        //
        // GET: /Golfer/

        public ActionResult Index()
        {
            var golfers = Golfer.Fetch("Order By Last ASC");
            return View(golfers);

            //var db = new Database(ConnectionHelper.ConnectionStringName);
            //var golfers = db.Query<Golfer>("SELECT * FROM Golfers");

            //return Json(golfers, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Add Golfer
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Golfer golferModel)
        {
            if(ModelState.IsValid)
            {
                // Create new Golfer object
                var newGolfer = new Golfer();

                // Set data
                newGolfer._First = golferModel._First;
                newGolfer.Last = golferModel.Last;
                newGolfer.FullName = golferModel._First + " " + golferModel.Last; 
                newGolfer.Email = golferModel.Email;

                newGolfer.Save();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// Edit Golfer
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            var golfer = Golfer.SingleOrDefault(id);
            return View(golfer);
        }

        [HttpPost]
        public ActionResult Edit(int id, Golfer golferModel)
        {
            if(ModelState.IsValid)
            {
                var golfer = Golfer.SingleOrDefault(id);

                golfer._First = golferModel._First;
                golfer.Last = golferModel.Last;
                golfer.FullName = golferModel._First + " " + golferModel.Last; 
                golfer.Email = golferModel.Email;

                golfer.Save();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// Delete Golfer
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            var golfer = Golfer.SingleOrDefault(id);
            return View(golfer);
        }

        [HttpPost]
        public ActionResult Delete(int id, Golfer golferModel)
        {
            var golfer = Golfer.SingleOrDefault(id);

            if(ModelState.IsValid)
            {
                golferModel.GolferID = id;
                golferModel.Delete();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
    }
}

Golf Roster Creator/Views/Golfer/Create.cshtml
@model Golf_Roster_Creator.Golfer

@{
    ViewBag.Title = "Create Golfer";
}
<div class="row">
    <div class="span12">
        <h2>@ViewBag.Title</h2>

        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)

            <div class="editor-container">
                <div class="editor-label">
                    @Html.LabelFor(model => model._First, "First name:")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model._First)
                    @Html.ValidationMessageFor(model => model._First)
                </div>
            </div>
            <div class="editor-container">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Last, "Last name:")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Last)
                    @Html.ValidationMessageFor(model => model.Last)
                </div>
            </div>
            <div class="editor-container">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Email, "Email Address:")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <p>
                <input type="submit" class="btn btn-info" value="Create" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn" })
            </p>
        }

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Golf Roster Creator/Views/Golfer/Delete.cshtml
@model Golf_Roster_Creator.Golfer

@{
    ViewBag.Title = "Delete Golfer?";
}

<div class="row">
    <div class="span12">
        <h2>@ViewBag.Title</h2>

        <h3>Are you sure you want to delete @Html.DisplayFor(model => model._First)?</h3>

        <div class="display-container">
            <div class="display-label">
                First name: 
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model._First)
            </div>
        </div>

        <div class="display-container">
            <div class="display-label">
                Last name:
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Last)
            </div>
        </div>

        <div class="display-container">
            <div class="display-label">
                Email Address:
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Email)
            </div>
        </div>

        @using (Html.BeginForm())
        {
            <p>
                <input type="submit" class="btn btn-info" value="Delete" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn" })
            </p>
        }
    </div>
</div>

Golf Roster Creator/Views/Golfer/Edit.cshtml
@model Golf_Roster_Creator.Golfer

@{
    ViewBag.Title = "Edit Golfer";
}

<div class="row">
    <div class="span12">

        <h2>@ViewBag.Title</h2>

        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)

            @Html.HiddenFor(model => model.GolferID)

            <div class="editor-container">
                <div class="editor-label">
                    @Html.LabelFor(model => model._First, "First name:")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model._First)
                    @Html.ValidationMessageFor(model => model._First)
                </div>
            </div>

            <div class="editor-container">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Last, "Last name:")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Last)
                    @Html.ValidationMessageFor(model => model.Last)
                </div>
            </div>

            <div class="editor-container">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Email, "Email Address:")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <p>
                <input type="submit" class="btn btn-primary" value="Save" />
                @Html.ActionLink("Cancel", "Index", "Golfer", null, new { @class = "btn" })
            </p>

        }

        <div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Golf Roster Creator/Views/Golfer/Index.cshtml
@model IEnumerable<Golf_Roster_Creator.Golfer>

@{
    ViewBag.Title = "Golfer Management";
}

<div class="row">
    <div class="span12">

        <h2>@ViewBag.Title</h2>

        <p>
            @Html.ActionLink("Add Golfer", "Create", "Golfer", null, new { @class = "btn btn-info" })
        </p>
        <table class="table table-condensed table-hover table-bordered">
            <thead>
                <tr>
                    <th>
                        <label>First name</label>
                    </th>
                    <th>
                        <label>Last name</label>
                    </th>
                    <th>
                        <label>Email Address</label>
                    </th>
                    <th></th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tbody>
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item._First)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Last)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.GolferID }, new { @class = "btn btn-success btn-small" })
                            @Html.ActionLink("Delete", "Delete", new { id = item.GolferID }, new { @class = "btn btn-small" })
                        </td>
                    </tr>
                </tbody>
            }

        </table>

    </div>
</div>