Golf Roster Creator/Golf Roster Creator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Golf_Roster_Creator.ViewModels;
using PetaPoco;
using Golf_Roster_Creator.Helpers;

namespace Golf_Roster_Creator.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(HomePageViewModel homePageViewModel)
        {
            var db = new Database(ConnectionHelper.ConnectionStringName);

            ViewBag.courses = new SelectList(db.Query<Course>("SELECT * FROM Courses ORDER BY Name ASC"), "Name", "Name");

            ViewBag.golfers = new SelectList(db.Query<Golfer>("SELECT * FROM Golfers ORDER BY Last ASC"), "GolferID", "FullName");

            ViewBag.teeTimes = db.Query<HomePageViewModel>("SELECT * FROM TeeTimes ORDER BY TeeTime ASC");

            return View(ViewBag.teeTimes);
        }

        public ActionResult test()
        {
            return View();
        }
    }
}

Golf Roster Creator/Golf Roster Creator/Controllers/TeeTimeController.cs
using Golf_Roster_Creator.Helpers;
using PetaPoco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Golf_Roster_Creator.Models;

namespace Golf_Roster_Creator.Controllers
{
    public class TeeTimeController : Controller
    {
        //
        // GET: /TeeTime/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        /// <summary>
        /// Create Tee Timee
        /// </summary>
        /// <param name="teeTimeModel"></param>
        /// <returns></returns>
        public ActionResult Create()
        {
            var db = new Database(ConnectionHelper.ConnectionStringName);
            ViewBag.golfers = new SelectList(db.Query<Golfer>("SELECT * FROM Golfers ORDER BY Last ASC"), "FullName", "FullName");

            return View();
        }

        [HttpPost]
        public ActionResult Create(TeeTime teeTimeModel)
        {
            if(ModelState.IsValid)
            {
                // String.Replace time
                var timeStringIndex = 0;
                var updatedTimeInput = "";
                var timeInput = teeTimeModel._TeeTime;

                timeStringIndex = timeInput.IndexOf("9:");

                // Create new object
                var newTeeTime = new TeeTime();

                if (timeStringIndex == 0)
                {
                    updatedTimeInput = timeInput.Replace("9:", "09:");
                    newTeeTime._TeeTime = updatedTimeInput;
                }
                else
                {
                    newTeeTime._TeeTime = teeTimeModel._TeeTime;
                }

                // Set data
                newTeeTime.Golfer1 = teeTimeModel.Golfer1;
                newTeeTime.Golfer2 = teeTimeModel.Golfer2;
                newTeeTime.Golfer3 = teeTimeModel.Golfer3;
                newTeeTime.Golfer4 = teeTimeModel.Golfer4;
                newTeeTime.Golfer5 = teeTimeModel.Golfer5;
                newTeeTime.WalkRide1 = teeTimeModel.WalkRide1;
                newTeeTime.WalkRide2 = teeTimeModel.WalkRide2;
                newTeeTime.WalkRide3 = teeTimeModel.WalkRide3;
                newTeeTime.WalkRide4 = teeTimeModel.WalkRide4;
                newTeeTime.WalkRide5 = teeTimeModel.WalkRide5;


                newTeeTime.Save();

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
    
        /// <summary>
        /// Edit Tee Time
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            var db = new Database(ConnectionHelper.ConnectionStringName);
            ViewBag.golfers = new SelectList(db.Query<Golfer>("SELECT * FROM Golfers ORDER BY Last ASC"), "FullName", "FullName");

            var teeTime = TeeTime.SingleOrDefault(id);
            return View(teeTime);
        }

        [HttpPost]
        public ActionResult Edit(int id, TeeTime teeTimeModel)
        {
            if(ModelState.IsValid)
            {
                // String.Replace time
                var timeStringIndex = 0;
                var updatedTimeInput = "";
                var timeInput = teeTimeModel._TeeTime;

                timeStringIndex = timeInput.IndexOf("9:");

                // Set data
                var teeTime = TeeTime.SingleOrDefault(id);

                if (timeStringIndex == 0)
                {
                    updatedTimeInput = timeInput.Replace("9:", "09:");
                    teeTime._TeeTime = updatedTimeInput;
                }
                else 
                {
                    teeTime._TeeTime = teeTimeModel._TeeTime;
                }
                
                teeTime.Golfer1 = teeTimeModel.Golfer1;
                teeTime.Golfer2 = teeTimeModel.Golfer2;
                teeTime.Golfer3 = teeTimeModel.Golfer3;
                teeTime.Golfer4 = teeTimeModel.Golfer4;
                teeTime.Golfer5 = teeTimeModel.Golfer5;
                teeTime.WalkRide1 = teeTimeModel.WalkRide1;
                teeTime.WalkRide2 = teeTimeModel.WalkRide2;
                teeTime.WalkRide3 = teeTimeModel.WalkRide3;
                teeTime.WalkRide4 = teeTimeModel.WalkRide4;
                teeTime.WalkRide5 = teeTimeModel.WalkRide5;

                teeTime.Save();

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// Delete all tee times
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            var teeTimes = TeeTime.SingleOrDefault(id);
            return View(teeTimes);
        }

        //
        // POST: /TeeTime/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, TeeTime teeTimeModel)
        {
            //var golfer = TeeTime.SingleOrDefault(id);

            if (ModelState.IsValid)
            {
                teeTimeModel.TeeTimeId = id;
                teeTimeModel.Delete();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
    }
}

Golf Roster Creator/Golf Roster Creator/Views/Home/Index.cshtml
@model IEnumerable<Golf_Roster_Creator.ViewModels.HomePageViewModel>

@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="span12">
        <!-- Course Selection -->
        <div class="golf-course alert alert-info">
            <div class="left">
                <strong><i class="icon-globe"></i>Select Golf Course: </strong>
                @Html.DropDownList("Course", (IEnumerable<SelectListItem>)ViewBag.courses, "--Select Course--", new { ng_model = "selectedCourse" })
            </div>
            <div class="right">
                <strong><i class="icon-calendar"></i>Date:</strong>
                <input type="text" ng-model="selectedDate" placeholder="Select date" />
            </div>
        </div>
    </div>
</div>
<div class="row course-info">
    <div class="span12">
        <span class="select-course">{{selectedCourse}}</span> - <span class="select-date">{{selectedDate}}</span>
    </div>
</div>

<div class="row">
    <div class="span12 tee-time-mgmt">
        @Html.ActionLink("Add 4-some / 5-some", "Create", "TeeTime", null, new { @class = "btn btn-info" }) 
        @Html.ActionLink("Reset", "Update", "TeeTime", null, new { @class = "btn" })
    </div>
</div>
<div class="row">
    @foreach (var item in Model) {
        <div class="span4">
            <fieldset class="well">
                <legend class="alert alert-success">Tee Time: @Html.DisplayFor(modelItem => item.TeeTime)</legend>
                <ul>
                    <li><i class="icon-user"></i>@Html.DisplayFor(modelItem => item.Golfer1) - <span>(@Html.DisplayFor(modelItem => item.WalkRide1))</span></li>
                    <li><i class="icon-user"></i>@Html.DisplayFor(modelItem => item.Golfer2) - <span>(@Html.DisplayFor(modelItem => item.WalkRide2))</span></li>
                    @if(item.Golfer3 != null){
                        <li><i class="icon-user"></i>@Html.DisplayFor(modelItem => item.Golfer3) - <span>(@Html.DisplayFor(modelItem => item.WalkRide3))</span></li>
                    }
                    @if(item.Golfer4 != null){
                        <li><i class="icon-user"></i>@Html.DisplayFor(modelItem => item.Golfer4) - <span>(@Html.DisplayFor(modelItem => item.WalkRide4))</span></li>
                    }
                    @if(item.Golfer5 != null){
                        <li><i class="icon-user"></i>@Html.DisplayFor(modelItem => item.Golfer5) - <span>(@Html.DisplayFor(modelItem => item.WalkRide5))</span></li>
                    }
                </ul>
                <p>
                    @Html.ActionLink("Edit Tee Time", "Edit", "TeeTime", new { id = item.TeeTimeId }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Delete", "Delete", "TeeTime", new { id = item.TeeTimeId }, new { @class = "btn" })
                </p>
            </fieldset>  
        </div>
    }
</div>

Golf Roster Creator/Golf Roster Creator/Views/Home/test.cshtml
@model IEnumerable<Golf_Roster_Creator.TeeTime>

@{
    ViewBag.Title = "test";
}

<h2>test</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model._TeeTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Golfer1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Golfer2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Golfer3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Golfer4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Golfer5)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item._TeeTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Golfer1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Golfer2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Golfer3)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Golfer4)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Golfer5)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TeeTimeId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TeeTimeId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TeeTimeId })
        </td>
    </tr>
}

</table>